import isPersian from "./isPersian/index";
import URLfix from "./URLfix/index";
import addOrdinalSuffix from "./addOrdinalSuffix/index";
import halfSpace from "./halfSpace/index";
import hasPersian from "./hasPersian/index";
import sheba from "./sheba/index";
import toPersianChars from "./toPersianChars/index";
import removeOrdinalSuffix from "./removeOrdinalSuffix/index";
import verifyIranianNationalId from "./nationalId/verifyIranianNationalId/index";
import getPlaceByIranNationalId from "./nationalId/getPlaceByIranNationalId/index";
import verifyCardNumber from "./bank/verifyCardNumber/index";
import getBankNameFromCardNumber from "./bank/getBankNameFromCardNumber/index";
import numberToWords from "./numberToWords/index";
import wordsToNumber from "./wordsToNumber/index";
import isArabic from "./isArabic/index";
import extractCardNumber from "./extractCardNumber/index";
import addCommas from "./commas/add/index";
import removeCommas from "./commas/remove/index";

export { isPersian, URLfix, addOrdinalSuffix, halfSpace, hasPersian, sheba, toPersianChars, removeOrdinalSuffix, verifyIranianNationalId, getPlaceByIranNationalId, verifyCardNumber, getBankNameFromCardNumber, numberToWords, wordsToNumber, isArabic, extractCardNumber, addCommas, removeCommas };
